// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABNKoaqYSSxngWv0dbk2cXOL96wMUG9UM',
    appId: '1:325264161432:web:adee8609bcc0c6115daeed',
    messagingSenderId: '325264161432',
    projectId: 'rollmark-app',
    authDomain: 'rollmark-app.firebaseapp.com',
    storageBucket: 'rollmark-app.appspot.com',
    measurementId: 'G-06DC305VG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBd_hlw3jDtSH0EOVQCesxT1ia2mFC3e0',
    appId: '1:325264161432:android:34483ab6f24d34c55daeed',
    messagingSenderId: '325264161432',
    projectId: 'rollmark-app',
    storageBucket: 'rollmark-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyr-XdN-j0cu9KFzOsHUhIy3RuaSU3POE',
    appId: '1:325264161432:ios:5eec348c8c10347e5daeed',
    messagingSenderId: '325264161432',
    projectId: 'rollmark-app',
    storageBucket: 'rollmark-app.appspot.com',
    iosClientId: '325264161432-78kioheop6v7gpon4uhckd3n1b094pdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.rollmark',
  );
}
